name: "Dependapager"
author: " Shaik Ajmal R"
description: "A workflow action to send you weekly dependabot alerts to slack and create Jira tickets"
branding:
  icon: 'alert-triangle'  
  color: 'red'
inputs:
  github_personal_token:
    description: " Github Personal Token to Query github for dependabot alerts"
    required: true
  slack_token:
    description: " Slack Bot Token to Send Alerts "
    required: true
  channel:
    description: " Slack Channel to Send the Alerts Too"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'


